Story5
iO-Academy/23-sept-catmode-bookswap-fe pull request #20
Opened 2023-11-02 16:52 UTC by henrymeager

Return book functionality has been added and styled to fit with mobile view

2023-11-02 20:00 UTC, Andrei-Trifu approved these changes
Great work! Looks good!

2023-11-03 09:36 UTC, ashleycoles requested changes
Really nice work, very very happy with the way it works - just a few things to tidy up!

2023-11-03 09:36 UTC, ashleycoles commented on src/Components/BookDetail/ReturnBook/ReturnBook.jsx
> +    fetch(`https://book-swap-api.dev.io-academy.uk/api/books/return/${bookID}`, {
Indention isn't quite right here

2023-11-03 09:36 UTC, ashleycoles commented on src/Components/BookDetail/ReturnBook/ReturnBook.jsx
> +            {
This bracket should be on the same line as (res) =>

2023-11-03 09:36 UTC, ashleycoles commented on src/Components/BookDetail/ReturnBook/ReturnBook.jsx
> +    const [name, setname] = useState('')
Doesn't look like this name state is used, you should remove it if not

2023-11-03 10:41 UTC, ashleycoles approved these changes

2023-11-03 10:41 UTC, merged